[scenario]
name = "Test"
description = "This is to test the editor"
iterations = 1000

[[defenders]]
name = "Factory"
staying_power = 4
magazine_depth = 0
max_engagement_capacity = 0
doctrine = "shoot-look-shoot"

[defenders.pkd]
type = "fixed"
value = 0.7

[[defenders]]
name = "S-300"
staying_power = 3
magazine_depth = 36
max_engagement_capacity = 12
doctrine = "shoot-look-shoot"

[defenders.pkd]
type = "normal_distribution"
mean = 0.85
std_dev = 0.5

[[defenders]]
name = "Pantsir-2M"
staying_power = 2
magazine_depth = 32
max_engagement_capacity = 8
doctrine = "shoot-look-shoot"

[defenders.pkd]
type = "normal_distribution"
mean = 0.75
std_dev = 0.1

[[attackers]]
name = "Drone Swarm"
target_name = "Factory"
salvo_schedule = [20, 10, 5]

[attackers.pko]
type = "normal_distribution"
mean = 0.7
std_dev = 0.25
